Repository ComputationalRadiationPhysics/isaac, pull requests merged in 2021-03, with the labels that each got.

#133 Uniform formatting with clang-format
  .clang-format
  example/example.cpp
  example/example_details.hpp
  lib/isaac.hpp
  lib/isaac/isaac_common_kernel.hpp
  lib/isaac/isaac_communicator.hpp
  lib/isaac/isaac_compositors.hpp
  lib/isaac/isaac_controllers.hpp
  lib/isaac/isaac_defines.hpp
  lib/isaac/isaac_functor_chain.hpp
  lib/isaac/isaac_functors.hpp
  lib/isaac/isaac_fusion_extension.hpp
  lib/isaac/isaac_helper.hpp
  lib/isaac/isaac_iso_kernel.hpp
  lib/isaac/isaac_macros.hpp
  lib/isaac/isaac_min_max_kernel.hpp
  lib/isaac/isaac_particle_kernel.hpp
  lib/isaac/isaac_ssao_kernel.hpp
  lib/isaac/isaac_types.hpp
  lib/isaac/isaac_volume_kernel.hpp
  server/src/Broker.cpp
  server/src/Broker.hpp
  server/src/Common.cpp
  server/src/Common.hpp
  server/src/ImageConnector.cpp
  server/src/ImageConnector.hpp
  server/src/InsituConnector.cpp
  server/src/InsituConnector.hpp
  server/src/InsituConnectorMaster.cpp
  server/src/InsituConnectorMaster.hpp
  server/src/MessageAble.hpp
  server/src/MetaDataClient.cpp
  server/src/MetaDataClient.hpp
  server/src/MetaDataConnector.cpp
  server/src/MetaDataConnector.hpp
  server/src/NetworkInterfaces.cpp
  server/src/NetworkInterfaces.hpp
  server/src/RTMPImageConnector.cpp
  server/src/RTMPImageConnector.hpp
  server/src/RTPImageConnector.cpp
  server/src/RTPImageConnector.hpp
  server/src/Runable.cpp
  server/src/Runable.hpp
  server/src/SDLImageConnector.cpp
  server/src/SDLImageConnector.hpp
  server/src/SaveFileImageConnector.cpp
  server/src/SaveFileImageConnector.hpp
  server/src/TCPDataConnector.cpp
  server/src/TCPDataConnector.hpp
  server/src/ThreadList.hpp
  server/src/URIImageConnector.cpp
  server/src/URIImageConnector.hpp
  server/src/WebSocketDataConnector.cpp
  server/src/WebSocketDataConnector.hpp
  server/src/isaac.cpp
  server/src/version.hpp
Labels: refactoring

#134 CMake: increase ISAAC compatibility
  INSTALL.md
  lib/ISAACConfig.cmake
Labels: enhancement

#135 fix glm support
  INSTALL.md
  lib/ISAACConfig.cmake
Labels: bug
