Repository ComputationalRadiationPhysics/isaac, pull requests merged in 2022-05, with the labels that each got.

#160 fix missing include
  lib/isaac/isaac_fusion_extension.hpp
Labels: bug

#161 fix CUDA 11.3 compatibility
  lib/isaac.hpp
  lib/isaac/isaac_iso_kernel.hpp
  lib/isaac/isaac_particle_kernel.hpp
  lib/isaac/isaac_volume_kernel.hpp
Labels: bug

#162 update version to 1.7.0
  lib/isaac/isaac_version.hpp
Labels: documentation

#163 changes from 1.5.2
  CHANGELOG.md
  INSTALL.md
  lib/isaac/isaac_version.hpp
  server/src/version.hpp
Labels: documentation

#165 Fix of the 'sum' function.
  lib/isaac/isaac_functors.hpp
Labels: bug

#166 Topic cherry pick sum bug
  .rodare.json
  lib/isaac/isaac_functors.hpp
Labels: bug

#164 Topic changelog v1.6.0
  CHANGELOG.md
  lib/isaac/isaac_version.hpp
Labels: documentation

#167 fix changelog
  CHANGELOG.md
Labels: bug, documentation

#168 merge release v1.6.0 changes to dev
  .rodare.json
  CHANGELOG.md
  INSTALL.md
Labels: documentation
