Repository ComputationalRadiationPhysics/isaac, pull requests merged in 2022-04, with the labels that each got.

#156 fix MPI waitall to run on crusher
  lib/isaac.hpp
Labels: bug

#157 fix CMake pThread integration
  lib/ISAACConfig.cmake
Labels: bug, library

#158 add HIP support
  lib/isaac.hpp
  lib/isaac/isaac_defines.hpp
  lib/isaac/isaac_kernel.hpp
Labels: enhancement, library

#159 boost fusion lists are not trvially copyable
  lib/isaac/isaac_fusion_extension.hpp
Labels: bug
